[package]
name = "seme"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.34"
colored = "2.1.0"
isahc = { version = "1.7.2", features = ["json"] }
itertools = "0.12.1"
linku-sona = "0.1"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
